/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author HP
 */
public class LihatTugas extends javax.swing.JFrame {

    Connection conn;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LihatTugas.class.getName());

    /**
     * Creates new form lihat_siswa
     */
    public LihatTugas() {
        initComponents();
        tampilData();
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("ID Mahasiswa");
        model.addColumn("ID Matakuliah");
        model.addColumn("Judul Tugas");
        model.addColumn("Deskripsi");
        model.addColumn("Tanggal Dibuat");
        model.addColumn("Deadline");
        model.addColumn("Status");

        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM tb_tugas";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_tugas"),
                    rs.getString("id_mahasiswa"),
                    rs.getString("id_matakuliah"),
                    rs.getString("judul_tugas"),
                    rs.getString("deskripsi_tugas"),
                    rs.getString("tanggal_dibuat"),
                    rs.getString("deadline"),
                    rs.getString("status_tugas")
                });
            }
            tabelLihatTugas.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan Data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLihatTugas = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Tugas");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari Tugas : ");

        txtCari.addActionListener(this::txtCariActionPerformed);
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tabelLihatTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelLihatTugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelLihatTugasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelLihatTugas);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        btnPrint.setText("Print");
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnCari)
                .addGap(18, 18, 18)
                .addComponent(btnPrint)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnCari)
                    .addComponent(btnPrint))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelLihatTugasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelLihatTugasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelLihatTugasKeyReleased

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        btnCariActionPerformed(null);
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("ID Mahasiswa");
        model.addColumn("ID Matakuliah");
        model.addColumn("Judul Tugas");
        model.addColumn("Deskripsi");
        model.addColumn("Tanggal Dibuat");
        model.addColumn("Deadline");
        model.addColumn("Status");

        try {
            Connection conn = Koneksi.getConnection();

            String keyword = txtCari.getText();

            String sql = "SELECT * FROM tb_tugas WHERE "
                    + "id_tugas LIKE ? OR "
                    + "judul_tugas LIKE ? OR "
                    + "deskripsi_tugas LIKE ? OR "
                    + "tanggal_dibuat LIKE ? OR "
                    + "deadline LIKE ? OR "
                    + "status_tugas LIKE ?";

            PreparedStatement pst = conn.prepareStatement(sql);

            for (int i = 1; i <= 6; i++) {
                pst.setString(i, "%" + keyword + "%");
            }

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_tugas"),
                    rs.getString("id_mahasiswa"),
                    rs.getString("id_matakuliah"),
                    rs.getString("judul_tugas"),
                    rs.getString("deskripsi_tugas"),
                    rs.getString("tanggal_dibuat"),
                    rs.getString("deadline"),
                    rs.getString("status_tugas")
                });
            }
            tabelLihatTugas.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal Mencari Data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            // Buat file HTML
            File file = new File("data_tugas.html");
            FileWriter fw = new FileWriter(file);

            // Tulis HTML
            fw.write("<html><head><title>Data Tugas</title></head><body>");
            fw.write("<h2>Daftar Tugas</h2>");
            fw.write("<table border='1' cellpadding='5' cellspacing='0'>");

            // Header tabel
            fw.write("<tr>"
                    + "<th>ID</th>"
                    + "<th>ID Mahasiswa</th>"
                    + "<th>ID Matakuliah</th>"
                    + "<th>Judul Tugas</th>"
                    + "<th>Deskripsi</th>"
                    + "<th>Tanggal Dibuat</th>"
                    + "<th>Deadline</th>"
                    + "<th>Status</th>"
                    + "</tr>");

            // Isi data dari tabel
            for (int i = 0; i < tabelLihatTugas.getRowCount(); i++) {
                fw.write("<tr>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 0) + "</td>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 1) + "</td>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 2) + "</td>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 3) + "</td>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 4) + "</td>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 5) + "</td>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 6) + "</td>"
                        + "<td>" + tabelLihatTugas.getValueAt(i, 7) + "</td>"
                        + "</tr>");
            }

            fw.write("</table></body></html>");
            fw.close();

            // Buka di browser
            Desktop.getDesktop().browse(file.toURI());

            JOptionPane.showMessageDialog(null,
                    "Data Berhasil Diekspor!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal Export: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LihatTugas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelLihatTugas;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
