/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author HP
 */
public class Tugas extends javax.swing.JFrame {

    Connection conn;
    String idTugas = "";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tugas.class.getName());

    /**
     * Creates new form matakuliah
     */
    public Tugas() {
        initComponents();
        tampilData();
        cmbStatus.setSelectedIndex(0);
        warnaStatus();
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Tugas");
        model.addColumn("ID Mahasiswa");
        model.addColumn("ID Matakuliah");
        model.addColumn("Judul Tugas");
        model.addColumn("Deskripsi");
        model.addColumn("Tanggal Dibuat");
        model.addColumn("Deadline");
        model.addColumn("Status");
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM tb_tugas";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_tugas"),
                    rs.getString("id_mahasiswa"),
                    rs.getString("id_matakuliah"),
                    rs.getString("judul_tugas"),
                    rs.getString("deskripsi_tugas"),
                    rs.getString("tanggal_dibuat"),
                    rs.getString("deadline"),
                    rs.getString("status_tugas")
                });
            }
            tabelTugas.setModel(model);
            warnaStatus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan Data : " + e.getMessage());
        }
    }
    
    private void warnaStatus() {
    tabelTugas.setDefaultRenderer(Object.class,
            new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
            java.awt.Component c =
                    super.getTableCellRendererComponent(
                            table, value, isSelected, hasFocus, row, column);
            String status = table.getValueAt(row, 7).toString();
            if (!isSelected) {
                if (status.equals("belum selesai")) {
                    c.setBackground(java.awt.Color.PINK);
                } else if (status.equals("proses")) {
                    c.setBackground(java.awt.Color.YELLOW);
                } else if (status.equals("selesai")) {
                    c.setBackground(java.awt.Color.GREEN);
                } else {
                    c.setBackground(java.awt.Color.WHITE);
                }
            }
            return c;
        }
    });
}

    private void bersihkanForm() {
        txtIdMahasiswa.setText("");
        txtIdMatkul.setText("");
        txtJudul.setText("");
        txtDeskripsi.setText("");
        dateDibuat.setDate(null);
        dateDeadline.setDate(null);
        cmbStatus.setSelectedIndex(0);
        idTugas = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdMahasiswa = new javax.swing.JTextField();
        txtIdMatkul = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTugas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        dateDibuat = new com.toedter.calendar.JDateChooser();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        dateDeadline = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtNamaMahasiswa = new javax.swing.JTextField();
        txtNamaMatkul = new javax.swing.JTextField();
        btnCariMahasiswa = new javax.swing.JButton();
        btnCariMatkul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtIdMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 96, 342, -1));

        txtIdMatkul.addActionListener(this::txtIdMatkulActionPerformed);
        jPanel1.add(txtIdMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 176, 342, -1));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel1.setText("Data Tugas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel3.setText("ID Mahasiswa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 99, -1, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel4.setText("ID Matkul");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 179, -1, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel5.setText("Tanggal Dibuat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 378, -1, -1));

        btnHapus.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnHapus.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(102, 0, 102));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 529, -1, -1));

        btnSimpan.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnSimpan.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(102, 0, 102));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 529, -1, -1));

        btnEdit.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnEdit.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(102, 0, 102));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 529, -1, -1));

        btnClear.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnClear.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(102, 0, 102));
        btnClear.setText("BATAL");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 529, -1, -1));

        tabelTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTugas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 622, 225));

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel6.setText("Status Tugas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 458, -1, -1));
        jPanel1.add(dateDibuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 378, 342, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "belum selesai", "proses", "selesai" }));
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 458, 342, -1));

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel7.setText("Judul Tugas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 259, -1, -1));

        txtJudul.addActionListener(this::txtJudulActionPerformed);
        jPanel1.add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 256, 342, -1));

        jLabel8.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel8.setText("Desk. Tugas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 296, -1, -1));

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 296, 342, 64));
        jPanel1.add(dateDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 418, 342, -1));

        jLabel10.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel10.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel10.setText("Deadline");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 418, -1, -1));

        txtNamaMahasiswa.setEditable(false);
        jPanel1.add(txtNamaMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 136, 240, -1));

        txtNamaMatkul.setEditable(false);
        jPanel1.add(txtNamaMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 216, 240, -1));

        btnCariMahasiswa.setText("Cek");
        btnCariMahasiswa.addActionListener(this::btnCariMahasiswaActionPerformed);
        jPanel1.add(btnCariMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 57, -1));

        btnCariMatkul.setText("Cek");
        btnCariMatkul.addActionListener(this::btnCariMatkulActionPerformed);
        jPanel1.add(btnCariMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 57, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMatkulActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // VALIDASI
        try {
            if (txtIdMahasiswa.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Mahasiswa harus diisi");
                return;
            }
            if (txtIdMatkul.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Matakuliah harus diisi");
                return;
            }
            if (txtJudul.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Judul tugas harus diisi");
                return;
            }
            if (dateDibuat.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Tanggal dibuat harus diisi");
                return;
            }
            if (dateDeadline.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Deadline harus diisi");
                return;
            }
            Connection conn = Koneksi.getConnection();
            String sql = "INSERT INTO tb_tugas "
                    + "(id_mahasiswa, id_matakuliah, judul_tugas, "
                    + "deskripsi_tugas, tanggal_dibuat, deadline, status_tugas) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtIdMahasiswa.getText());
            pst.setString(2, txtIdMatkul.getText());
            pst.setString(3, txtJudul.getText());
            pst.setString(4, txtDeskripsi.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            pst.setString(5, sdf.format(dateDibuat.getDate()));
            pst.setString(6, sdf.format(dateDeadline.getDate()));
            pst.setString(7, cmbStatus.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            tampilData();
            // Reset form
            txtIdMahasiswa.setText("");
            txtIdMatkul.setText("");
            txtJudul.setText("");
            txtDeskripsi.setText("");
            dateDibuat.setDate(null);
            dateDeadline.setDate(null);
            cmbStatus.setSelectedIndex(0);
            idTugas = "";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan : " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            if (idTugas.equals("")) {
                JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
                return;
            }
            int konfirmasi = JOptionPane.showConfirmDialog(null,
                    "Yakin ingin menghapus data ini?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                Connection conn = Koneksi.getConnection();
                String sql = "DELETE FROM tb_tugas WHERE id_tugas=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, idTugas);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                tampilData();
                txtIdMahasiswa.setText("");
                txtIdMatkul.setText("");
                txtJudul.setText("");
                txtDeskripsi.setText("");
                dateDibuat.setDate(null);
                dateDeadline.setDate(null);
                cmbStatus.setSelectedIndex(0);
                idTugas = "";
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus : " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            if (idTugas.equals("")) {
                JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
                return;
            }
            Connection conn = Koneksi.getConnection();
            String sql = "UPDATE tb_tugas SET "
                    + "id_mahasiswa=?, id_matakuliah=?, judul_tugas=?, "
                    + "deskripsi_tugas=?, tanggal_dibuat=?, deadline=?, status_tugas=? "
                    + "WHERE id_tugas=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtIdMahasiswa.getText());
            pst.setString(2, txtIdMatkul.getText());
            pst.setString(3, txtJudul.getText());
            pst.setString(4, txtDeskripsi.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            pst.setString(5, sdf.format(dateDibuat.getDate()));
            pst.setString(6, sdf.format(dateDeadline.getDate()));
            pst.setString(7, cmbStatus.getSelectedItem().toString());
            pst.setString(8, idTugas);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            tampilData();
            // Reset form
            txtIdMahasiswa.setText("");
            txtIdMatkul.setText("");
            txtJudul.setText("");
            txtDeskripsi.setText("");
            dateDibuat.setDate(null);
            dateDeadline.setDate(null);
            cmbStatus.setSelectedIndex(0);
            idTugas = "";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah : " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtNamaMahasiswa.setText("");
        txtNamaMatkul.setText("");
        txtIdMahasiswa.setText("");
        txtIdMatkul.setText("");
        txtJudul.setText("");
        txtDeskripsi.setText("");
        dateDibuat.setDate(null);
        dateDeadline.setDate(null);
        cmbStatus.setSelectedIndex(0);
        idTugas = "";
    }//GEN-LAST:event_btnClearActionPerformed

    private void tabelTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTugasMouseClicked
        // TODO add your handling code here:
        int baris = tabelTugas.getSelectedRow();
        idTugas = tabelTugas.getValueAt(baris, 0).toString();
        txtIdMahasiswa.setText(tabelTugas.getValueAt(baris, 1).toString());
        txtIdMatkul.setText(tabelTugas.getValueAt(baris, 2).toString());
        txtJudul.setText(tabelTugas.getValueAt(baris, 3).toString());
        txtDeskripsi.setText(tabelTugas.getValueAt(baris, 4).toString());

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dateDibuat.setDate(sdf.parse(tabelTugas.getValueAt(baris, 5).toString()));
            dateDeadline.setDate(sdf.parse(tabelTugas.getValueAt(baris, 6).toString()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tanggal gagal ditampilkan");
        }

        cmbStatus.setSelectedItem(tabelTugas.getValueAt(baris, 7).toString());
    }//GEN-LAST:event_tabelTugasMouseClicked

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void btnCariMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariMahasiswaActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdMahasiswa.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Mahasiswa harus diisi dulu");
                return;
            }
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM tb_mahasiswa WHERE id_mahasiswa=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtIdMahasiswa.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtNamaMahasiswa.setText(rs.getString("nama_mahasiswa"));
            } else {
                JOptionPane.showMessageDialog(null, "ID Mahasiswa tidak ditemukan");
                txtNamaMahasiswa.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariMahasiswaActionPerformed

    private void btnCariMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariMatkulActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdMatkul.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Matakuliah harus diisi dulu");
                return;
            }
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM tb_matakuliah WHERE id_matakuliah=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtIdMatkul.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtNamaMatkul.setText(rs.getString("nama_matakuliah"));
            } else {
                JOptionPane.showMessageDialog(null, "ID Matakuliah tidak ditemukan");
                txtNamaMatkul.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariMatkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tugas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariMahasiswa;
    private javax.swing.JButton btnCariMatkul;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbStatus;
    private com.toedter.calendar.JDateChooser dateDeadline;
    private com.toedter.calendar.JDateChooser dateDibuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelTugas;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtIdMahasiswa;
    private javax.swing.JTextField txtIdMatkul;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtNamaMahasiswa;
    private javax.swing.JTextField txtNamaMatkul;
    // End of variables declaration//GEN-END:variables
}
