/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mahasiswa;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

public class Mahasiswa extends javax.swing.JFrame {

    Connection conn;
    String selectedId = "";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mahasiswa.class.getName());

    /**
     * Creates new form mahasiswa
     */
    public Mahasiswa() {
        initComponents();
        tampilData();
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("NIM");
        model.addColumn("Jurusan");
        model.addColumn("No HP");

        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM tb_mahasiswa";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_mahasiswa"),
                    rs.getString("nama_mahasiswa"),
                    rs.getString("nim"),
                    rs.getString("jurusan"),
                    rs.getString("no_hp")
                });
            }
            tabelMahasiswa.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }

    private void bersihkanForm() {
        txtNama.setText("");
        txtNIM.setText("");
        txtJurusan.setText("");
        txtNoHP.setText("");
        selectedId = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtJurusan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNoHP = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();

        jLabel4.setText("jLabel1");

        jTextField3.setText("jTextField1");

        jTextField5.setText("jTextField1");

        jLabel6.setText("jLabel1");

        jButton4.setText("jButton1");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel2.setText("Tambah Data Mahasiswa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        txtNama.addActionListener(this::txtNamaActionPerformed);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 352, -1));

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel1.setText("Nama Mahasiswa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel3.setText("NIM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, -1));
        jPanel1.add(txtNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 352, -1));

        txtJurusan.addActionListener(this::txtJurusanActionPerformed);
        jPanel1.add(txtJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 352, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel5.setText("Jurusan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, -1));

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel7.setText("No. HP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, -1));

        txtNoHP.addActionListener(this::txtNoHPActionPerformed);
        jPanel1.add(txtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 352, -1));

        btnSimpan.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnSimpan.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(102, 0, 102));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        btnBatal.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnBatal.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(102, 0, 102));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        btnHapus.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnHapus.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(102, 0, 102));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        btnEdit.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnEdit.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(102, 0, 102));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMahasiswa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 303, 571, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin mau hapus data ini?");
        if (confirm == 0) {
            try {
                Connection conn = Koneksi.getConnection();
                String sql = "DELETE FROM tb_mahasiswa WHERE id_mahasiswa=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, selectedId);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
                bersihkanForm();
                tampilData();
                btnSimpan.setEnabled(true);
                btnEdit.setEnabled(false);
                btnHapus.setEnabled(false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "UPDATE tb_mahasiswa SET nama_mahasiswa=?, nim=?, jurusan=?, no_hp=? WHERE id_mahasiswa=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNama.getText());
            pst.setString(2, txtNIM.getText());
            pst.setString(3, txtJurusan.getText());
            pst.setString(4, txtNoHP.getText());
            pst.setString(5, selectedId);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate!");
            bersihkanForm();
            tampilData();
            btnSimpan.setEnabled(true);
            btnEdit.setEnabled(false);
            btnHapus.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHPActionPerformed

    private void txtJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJurusanActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        // TODO add your handling code here:
        int baris = tabelMahasiswa.getSelectedRow();
        selectedId = tabelMahasiswa.getValueAt(baris, 0).toString();
        txtNama.setText(tabelMahasiswa.getValueAt(baris, 1).toString());
        txtNIM.setText(tabelMahasiswa.getValueAt(baris, 2).toString());
        txtJurusan.setText(tabelMahasiswa.getValueAt(baris, 3).toString());
        txtNoHP.setText(tabelMahasiswa.getValueAt(baris, 4).toString());

        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "INSERT INTO tb_mahasiswa (nama_mahasiswa, nim, jurusan, no_hp) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNama.getText());
            pst.setString(2, txtNIM.getText());
            pst.setString(3, txtJurusan.getText());
            pst.setString(4, txtNoHP.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            bersihkanForm();
            tampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        bersihkanForm();
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JTextField txtJurusan;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHP;
    // End of variables declaration//GEN-END:variables
}
