/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notifikasi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author HP
 */
public class Notifikasi extends javax.swing.JFrame {

    Connection conn;
    String selectedId = "";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Notifikasi.class.getName());

    /**
     * Creates new form matakuliah
     */
    public Notifikasi() {
        initComponents();
        tampilData();
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("ID Tugas");
        model.addColumn("Pesan");
        model.addColumn("Tanggal Notifikasi");
        model.addColumn("Status");

        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM tb_notifikasi";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_notifikasi"),
                    rs.getString("id_tugas"),
                    rs.getString("pesan_notifikasi"),
                    rs.getString("tanggal_notifikasi"),
                    rs.getString("status_notifikasi")
                });
            }
            tabelNotifikasi.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan Data: " + e.getMessage());
        }
    }

    private void bersihkanForm() {
        txtIdTugas.setText("");
        txtPesan.setText("");
        dateNotifikasi.setDate(null);
        cmbStatus.setSelectedIndex(0);
        selectedId = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdTugas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNotifikasi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        dateNotifikasi = new com.toedter.calendar.JDateChooser();
        cmbStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPesan = new javax.swing.JTextArea();
        txtJudulTugas = new javax.swing.JTextField();
        btnCariTugas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtIdTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 342, -1));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel1.setText("Data Notifikasi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel3.setText("ID Tugas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 103, -1, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel4.setText("Pesan Notif");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel5.setText("Tanggal Notif");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        btnHapus.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnHapus.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(102, 0, 102));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        btnSimpan.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnSimpan.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(102, 0, 102));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        btnEdit.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnEdit.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(102, 0, 102));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        btnBatal.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnBatal.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(102, 0, 102));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        tabelNotifikasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelNotifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNotifikasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNotifikasi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 622, 225));

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel6.setText("Status Notif");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        jPanel1.add(dateNotifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 342, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BELUM DIBACA", "SUDAH DIBACA" }));
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 342, -1));

        txtPesan.setColumns(20);
        txtPesan.setRows(5);
        jScrollPane2.setViewportView(txtPesan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 342, 52));

        txtJudulTugas.setEditable(false);
        txtJudulTugas.addActionListener(this::txtJudulTugasActionPerformed);
        jPanel1.add(txtJudulTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 270, -1));

        btnCariTugas.setText("Cari");
        btnCariTugas.addActionListener(this::btnCariTugasActionPerformed);
        jPanel1.add(btnCariTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 140, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // VALIDASI
        if (txtIdTugas.getText().trim().isEmpty()
                || txtPesan.getText().trim().isEmpty()
                || dateNotifikasi.getDate() == null) {

            JOptionPane.showMessageDialog(null,
                    "Semua field wajib harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Connection conn = Koneksi.getConnection();

            String sql = "INSERT INTO tb_notifikasi "
                    + "(id_tugas, pesan_notifikasi, tanggal_notifikasi, status_notifikasi) "
                    + "VALUES (?, ?, ?, ?)";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtIdTugas.getText());
            pst.setString(2, txtPesan.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String tanggal = sdf.format(dateNotifikasi.getDate());
            pst.setString(3, tanggal);

            pst.setString(4, cmbStatus.getSelectedItem().toString());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,
                    "Data Berhasil Disimpan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            bersihkanForm();
            tampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Data Gagal Disimpan: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:

        if (selectedId.equals("")) {
            JOptionPane.showMessageDialog(null,
                    "Pilih data yang akan dihapus terlebih dahulu");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null,
                "Yakin mau hapus data ini?");

        if (confirm == 0) {
            try {
                Connection conn = Koneksi.getConnection();
                String sql = "DELETE FROM tb_notifikasi WHERE id_notifikasi=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, selectedId);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");

                bersihkanForm();
                tampilData();
                btnSimpan.setEnabled(true);
                btnEdit.setEnabled(false);
                btnHapus.setEnabled(false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Gagal Hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        if (selectedId.equals("")) {
            JOptionPane.showMessageDialog(null,
                    "Pilih data yang akan diedit terlebih dahulu");
            return;
        }

        try {
            Connection conn = Koneksi.getConnection();

            String sql = "UPDATE tb_notifikasi SET "
                    + "id_tugas=?, pesan_notifikasi=?, "
                    + "tanggal_notifikasi=?, status_notifikasi=? "
                    + "WHERE id_notifikasi=?";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtIdTugas.getText());
            pst.setString(2, txtPesan.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String tanggal = sdf.format(dateNotifikasi.getDate());
            pst.setString(3, tanggal);

            pst.setString(4, cmbStatus.getSelectedItem().toString());
            pst.setString(5, selectedId);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate!");

            bersihkanForm();
            tampilData();
            btnSimpan.setEnabled(true);
            btnEdit.setEnabled(false);
            btnHapus.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal Update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        bersihkanForm();
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        txtJudulTugas.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tabelNotifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNotifikasiMouseClicked
        // TODO add your handling code here:
        int baris = tabelNotifikasi.getSelectedRow();

        selectedId = tabelNotifikasi.getValueAt(baris, 0).toString();
        txtIdTugas.setText(tabelNotifikasi.getValueAt(baris, 1).toString());
        txtPesan.setText(tabelNotifikasi.getValueAt(baris, 2).toString());

        try {
            String tanggal = tabelNotifikasi.getValueAt(baris, 3).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date dt = sdf.parse(tanggal);
            dateNotifikasi.setDate(dt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tanggal gagal ditampilkan");
        }

        cmbStatus.setSelectedItem(tabelNotifikasi.getValueAt(baris, 4).toString());

        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tabelNotifikasiMouseClicked

    private void btnCariTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTugasActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdTugas.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Tugas harus diisi dulu");
                return;
            }
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM tb_tugas WHERE id_tugas=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtIdTugas.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtJudulTugas.setText(rs.getString("judul_tugas"));
            } else {
                JOptionPane.showMessageDialog(null, "ID Tugas tidak ditemukan");
                txtJudulTugas.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariTugasActionPerformed

    private void txtJudulTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulTugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Notifikasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariTugas;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbStatus;
    private com.toedter.calendar.JDateChooser dateNotifikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelNotifikasi;
    private javax.swing.JTextField txtIdTugas;
    private javax.swing.JTextField txtJudulTugas;
    private javax.swing.JTextArea txtPesan;
    // End of variables declaration//GEN-END:variables
}
